// ══════════════════════════════════════════════════════════════════════
// Genesis Nutrition — Cloud Functions
// ══════════════════════════════════════════════════════════════════════

const {onDocumentCreated} = require('firebase-functions/v2/firestore');
const {defineSecret} = require('firebase-functions/params');
const {initializeApp} = require('firebase-admin/app');
const {getFirestore, FieldValue} = require('firebase-admin/firestore');
const nodemailer = require('nodemailer');

initializeApp();

// Secret for Gmail app password. Set via:
//   firebase functions:secrets:set GMAIL_APP_PASSWORD
// (you'll paste the password in a prompt, it won't be in source)
const GMAIL_APP_PASSWORD = defineSecret('GMAIL_APP_PASSWORD');

// ══════════════════════════════════════════════════════════════════════
// mirrorFriendship
// When a user writes a friendship edge (accepts a request), write the
// reverse edge automatically so BOTH sides see the friendship.
// ══════════════════════════════════════════════════════════════════════
exports.mirrorFriendship = onDocumentCreated(
  'friendships/{uid}/list/{friendUid}',
    async (event) => {
        const {uid, friendUid} = event.params;

            const db = getFirestore();
                const reverseRef = db
                      .collection('friendships')
                            .doc(friendUid)
                                  .collection('list')
                                        .doc(uid);

                                            const reverse = await reverseRef.get();
                                                if (reverse.exists) {
                                                      console.log(`Reverse edge ${friendUid}->${uid} already exists, skipping`);
                                                            return;
                                                                }

                                                                    let senderUsername = '';
                                                                        try {
                                                                              const senderDoc = await db.collection('users').doc(uid).get();
                                                                                    if (senderDoc.exists) {
                                                                                            senderUsername = senderDoc.data().username || '';
                                                                                                  }
                                                                                                      } catch (e) {
                                                                                                            console.error('Username lookup failed:', e);
                                                                                                                }

                                                                                                                    await reverseRef.set({
                                                                                                                          username: senderUsername,
                                                                                                                                since: FieldValue.serverTimestamp(),
                                                                                                                                      mirroredBy: 'cloud-function',
                                                                                                                                          });

                                                                                                                                              console.log(`Mirrored friendship ${uid} -> ${friendUid}`);

                                                                                                                                                  try {
                                                                                                                                                        await db
                                                                                                                                                                .collection('friend_requests')
                                                                                                                                                                        .doc(friendUid)
                                                                                                                                                                                .collection('incoming')
                                                                                                                                                                                        .doc(uid)
                                                                                                                                                                                                .delete();
                                                                                                                                                                                                    } catch (e) {
                                                                                                                                                                                                          // not fatal
                                                                                                                                                                                                              }
                                                                                                                                                                                                                }
                                                                                                                                                                                                                );

                                                                                                                                                                                                                // ══════════════════════════════════════════════════════════════════════
                                                                                                                                                                                                                // notifyOnReport
                                                                                                                                                                                                                // When a user submits an abuse report, email the admin immediately.
                                                                                                                                                                                                                // Uses Gmail SMTP via Nodemailer with an App Password stored as a secret.
                                                                                                                                                                                                                // ══════════════════════════════════════════════════════════════════════
                                                                                                                                                                                                                exports.notifyOnReport = onDocumentCreated(
                                                                                                                                                                                                                  {
                                                                                                                                                                                                                      document: 'reports/{reportId}',
                                                                                                                                                                                                                          secrets: [GMAIL_APP_PASSWORD],
                                                                                                                                                                                                                            },
                                                                                                                                                                                                                              async (event) => {
                                                                                                                                                                                                                                  const report = event.data.data();
                                                                                                                                                                                                                                      const reportId = event.params.reportId;

                                                                                                                                                                                                                                          // Admin email — this is where reports go
                                                                                                                                                                                                                                              const ADMIN_EMAIL = '[email protected]';
                                                                                                                                                                                                                                                  const FROM_EMAIL = '[email protected]';

                                                                                                                                                                                                                                                      // Build email body
                                                                                                                                                                                                                                                          const lines = [];
                                                                                                                                                                                                                                                              lines.push(`Report ID: ${reportId}`);
                                                                                                                                                                                                                                                                  lines.push(`Type: ${report.type || 'user'}`);
                                                                                                                                                                                                                                                                      lines.push(`Submitted: ${new Date().toISOString()}`);
                                                                                                                                                                                                                                                                          lines.push('');
                                                                                                                                                                                                                                                                              lines.push(`Reporter: @${report.reporterUsername || '(unknown)'} (${report.reporterUid})`);
                                                                                                                                                                                                                                                                                  lines.push(`Reported: @${report.reportedUsername || '(unknown)'} (${report.reportedUid})`);
                                                                                                                                                                                                                                                                                      lines.push('');
                                                                                                                                                                                                                                                                                          lines.push(`Reason given:`);
                                                                                                                                                                                                                                                                                              lines.push(report.reason || '(no reason)');
                                                                                                                                                                                                                                                                                                  lines.push('');

                                                                                                                                                                                                                                                                                                      if (report.messageText) {
                                                                                                                                                                                                                                                                                                            lines.push('─'.repeat(50));
                                                                                                                                                                                                                                                                                                                  lines.push('REPORTED MESSAGE CONTENT:');
                                                                                                                                                                                                                                                                                                                        lines.push(report.messageText);
                                                                                                                                                                                                                                                                                                                              lines.push('─'.repeat(50));
                                                                                                                                                                                                                                                                                                                                    lines.push(`Conversation ID: ${report.conversationId || '(n/a)'}`);
                                                                                                                                                                                                                                                                                                                                          lines.push(`Message ID: ${report.messageId || '(n/a)'}`);
                                                                                                                                                                                                                                                                                                                                                lines.push(`Sent at: ${report.messageSentAt ? new Date(report.messageSentAt).toISOString() : '(n/a)'}`);
                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                        lines.push('');
                                                                                                                                                                                                                                                                                                                                                            lines.push('Review this report in the Firebase Console:');
                                                                                                                                                                                                                                                                                                                                                                lines.push(`https://console.firebase.google.com/project/genesis-nutrition-5d6f8/firestore/data/~2Freports~2F${reportId}`);
                                                                                                                                                                                                                                                                                                                                                                    lines.push('');
                                                                                                                                                                                                                                                                                                                                                                        lines.push('--');
                                                                                                                                                                                                                                                                                                                                                                            lines.push('Genesis Nutrition automated moderation notification');

                                                                                                                                                                                                                                                                                                                                                                                const body = lines.join('\n');

                                                                                                                                                                                                                                                                                                                                                                                    const subject = report.type === 'message'
                                                                                                                                                                                                                                                                                                                                                                                          ? `[Genesis Report] Message reported by @${report.reporterUsername}`
                                                                                                                                                                                                                                                                                                                                                                                                : report.type === 'filter_violation'
                                                                                                                                                                                                                                                                                                                                                                                                      ? `[Genesis Report] Auto-flag: content filter repeat violation`
                                                                                                                                                                                                                                                                                                                                                                                                            : `[Genesis Report] User reported by @${report.reporterUsername}`;

                                                                                                                                                                                                                                                                                                                                                                                                                // Create nodemailer transporter using Gmail SMTP
                                                                                                                                                                                                                                                                                                                                                                                                                    const transporter = nodemailer.createTransport({
                                                                                                                                                                                                                                                                                                                                                                                                                          service: 'gmail',
                                                                                                                                                                                                                                                                                                                                                                                                                                auth: {
                                                                                                                                                                                                                                                                                                                                                                                                                                        user: FROM_EMAIL,
                                                                                                                                                                                                                                                                                                                                                                                                                                                pass: GMAIL_APP_PASSWORD.value(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                      },
                                                                                                                                                                                                                                                                                                                                                                                                                                                          });

                                                                                                                                                                                                                                                                                                                                                                                                                                                              try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    await transporter.sendMail({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            from: `Genesis Moderation <${FROM_EMAIL}>`,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    to: ADMIN_EMAIL,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            subject: subject,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    text: body,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                console.log(`Report email sent for ${reportId}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } catch (e) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          console.error('Report email send failed:', e);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Don't throw — we don't want to retry indefinitely for email failures.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      // The report doc is preserved in Firestore regardless.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            